# Site settings
title: Rafael Ferreira
email:
description: > # this means to ignore newlines until "baseurl:"
  Descrição
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rafaelblink.github.io" # the base hostname & protocol for your site
twitter_username: rafaelblink
github_username: rafaelblink

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
